{
  "extends": "stylelint-config-standard",
  "rules": {
    "number-leading-zero": null,
    "max-empty-lines": null,
    "empty-lines": ["ignore"],
    "rule-empty-line-before": null,
    "no-eol-whitespace": null,
    "comment-empty-line-before": null,
    "*-empty-line-after": null,
    "multiline-ternary": ["always-multiline"]
  }


}
