extends:
  - stylelint-config-standard
ignoreFiles:
  - node_modules/**/*
rules:
   number-leading-zero: null,
   max-empty-lines: null,
   empty-lines: null,
   rule-empty-line-before: null,
   no-eol-whitespace: ["ignore", "empty-lines"],
   comment-empty-line-before: null,
   multiline-ternary: [true, "always-multiline"]
