---

extends:
  - stylelint-config-standard
  - stylelint-config-recommended-scss
ignoreFiles:
  - node_modules/**/*
  
rules:
  number-leading-zero: 
    - false
  max-empty-lines: 
    - false
  empty-lines: 
    - false
  no-eol-whitespace: 
    - [ true, { "ignore": "empty-lines"} ]
  comment-empty-line-before: 
    - false
   
  ## Labels
  no-unused-labels: 
    - false
  no-label-var: 
    - false
  multiline-ternary:
    - 2
    - always-multiline
  no-multiple-empty-lines:
    - 0 
  no-trailing-spaces: 
    - 0 
  no-whitespace-before-property: 
    - 0
     
  
 

  
  

      

 

  
  
  
