const actionTypes = {
  GAME_RULES: 'GAME_RULES',
  GUESSED_SUCCESS: 'GUESSED_SUCCESS',
  SET_SECRET_WORD: 'SET_SECRET_WORD',
  GUESSED_WORDS: 'GUESSED_WORDS',
  GUESSED_WORD: 'GUESSED_WORD',
  ON_SUBMIT_GUESS: 'ON_SUBMIT_GUESS',
  ON_CHANGE_GUESS: 'ON_CHANGE_GUESS'
}

export default actionTypes
