
name: Lint Code Base





# Start the job on all push 
# -------------------------
on:
  push:
   
  pull_request:
    branches: [master]


jobs:
  build:
    
    name: Lint Code Base
  
    runs-on: ubuntu-latest

   
    steps:
      
      # Checkout the code base
      # ----------------------
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history 
          fetch-depth: 0
        
      

     
      # Run Linter against code base 
      # ----------------------------
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
         
          
          # Dont lint test folder: 
         # FILTER_REGEX_EXCLUDE: .*test/.*
          
          # Validate Markdown
          VALIDATE_MARKDOWN: false
          
         
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
         
          
