---

## Linter GitHub Actions ##
###########################

name: Lint Code Base


#############################
# Start the job on all push #
#############################
on:
  push:
    # branches-ignore: []
    # Remove the line above to run when pushing to master
  pull_request:



###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
   
    runs-on: ubuntu-18.04 

  
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
         
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
        
        
          
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
          ACTIONS_RUNNER_DEBUG: true
          ANSIBLE_DIRECTORY: /src
          # CSS_FILE_NAME: .stylelintrc.yml
          
          FILTER_REGEX_EXCLUDE: .*src/.*
          
          IGNORE_GITIGNORED_FILES: true
          
          # JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          
          # JAVASCRIPT_DEFAULT_STYLE: prettier
          
          LOG_FILE: super-linter.log
          
          LOG_LEVEL: verbose
          
          OUTPUT_FOLDER: linter-report
          
          OUTPUT_DETAILS: detailed
          
          VALIDATE_ALL_CODEBASE: false  # only changes, edited files
          
          VALIDATE_MARKDOWN: false
          
          
   #  Badge       
   #  [![GitHub Super-Linter](https://github.com/stefan22/guessing-game/workflows/Lint%20Code%20Base/badge.svg)]
   #  (https://github.com/marketplace/actions/super-linter) 
   
   # . [![JavaScript Style Guide](https://img.shields.io/badge/code_style-standard-brightgreen.svg)](https://github.com/stefan22/guessing-game.git)
