
name: CI

on:
  # push,pull on master branch
  push:
  pull_request:
    branches: [ master ]



jobs:

  build:
   
    runs-on: ubuntu-latest

   
    steps:
    
     - name: Checkout Code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
         
       # Run linter against code base
     - name: Lint Code Base
       uses: github/super-linter@v3
       env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
         
          # Dont lint test folder: 
          #FILTER_REGEX_EXCLUDE: .*test/.*
          
          # Validate Markdown
          VALIDATE_MARKDOWN: false
          
         
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    


      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
        #run: |
         # echo Add other actions to build,
         # echo test, and deploy your project.
